---
filing_month: dec 2021
lse_map_file: 'M:\Users\RH2\src\resource_adequacy_reports\lse_map.yaml'
email_filter_file: 'M:\Users\RH2\src\resource_adequacy_reports\email_filter.yaml'
temp_directory: 'M:\Users\RH2\src\resource_adequacy_reports\temp'
ra_monthly_filing_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\filings\[lse_full]_[yyyy]\RAFiling_[yyyy]-[mm]_[lse_abbrev].xlsx'
incremental_local_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\validation_files\[yyyy]IncrementalLocal.xlsx'
cam_rmr_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\validation_files\CAM-RMR.xlsx'
ra_summary_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\validation_files\[mmm]MA[yy]RASummary_Testing.xlsx'
month_ahead_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\validation_files\MonthAheadForecastSummary[yyyy].xlsx'
year_ahead_filename_template: 'M:\Users\RH2\src\resource_adequacy_reports\validation_files\YearAhead[yyyy].xlsx'
webdriver_directory: 'M:\Users\RH2\src\resource_adequacy_reports\webdrivers'
browser: firefox
browser_action_timer: 0.65
browser_action_retries: 25
browser_headless: yes
log_file: 'M:\Users\RH2\src\resource_adequacy_reports\logs\ra_reports_retrieval.log'
cli_logging_criticalities: ERROR,WARNING,INFORMATION
file_logging_criticalities: ERROR
...