---
filing_month: apr 2022
planning_reserve_margin: 0.17
demand_response_multiplier: 1.09
transmission_loss_adder_pge: 1.03
transmission_loss_adder_sce: 1.025
transmission_loss_adder_sdge: 1.025
email_filter_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\config\email_filter.yaml'
kiteworks_hostname: 'https://kwftp.cpuc.ca.gov'
kiteworks_upload_folder: 'f1405d45-fe98-4ed2-9dfa-e12f6a226f1f'
archive_root_directory: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings'
organizations_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\config\organizations.yaml'
downloads_internal_directory: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\downloads\[yyyy]-[mm]\internal'
downloads_external_directory: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\downloads\[yyyy]-[mm]\external'
ra_monthly_filing_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\filings\[yyyy]-[mm]\RAFiling_[yyyy]-[mm]_[organization_id]_rev[version].xlsx'
month_ahead_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\requirements\[yyyy]_MonthAheadForecastSummary_rev[version].xlsx'
cam_rmr_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\requirements\[yyyy]-[mm]_CAM-RMR_rev[version].xlsx'
year_ahead_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\requirements\[yyyy]_YearAhead_rev[version].xlsx'
incremental_local_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\requirements\[yyyy]_IncrementalLocal_rev[version].xlsx'
supply_plan_system_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\supply_plans\[yyyy]-[mm]_CAISO_SupplyPlan_System_rev[version].xls'
supply_plan_flexible_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\supply_plans\[yyyy]-[mm]_CAISO_SupplyPlan_Flexible_rev[version].xls'
nqc_list_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\nqc_lists\[yyyy]_NQC_List_rev[version].xlsx'
ra_summary_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\results\MA_RASummary_[yyyy]-[mm].xlsx'
ra_summary_template_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\templates\RASummary_template_[yyyy].xlsx'
caiso_cross_check_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\results\RA_CAISO_SupplyPlan_CrossCheck_[yyyy]-[mm].xlsx'
caiso_cross_check_template_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\templates\RA_CAISO_SupplyPlan_Crosscheck_template.xlsx'
results_archive_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\archives\RAFilings_[yyyy]-[mm].zip'
ezdb_root_directory: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data'
ezdb_data_sources_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\data_sources\data_sources_[yyyy]-[mm].csv'
ezdb_organizations_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\organizations\organizations_[yyyy]-[mm].csv'
ezdb_requirements_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\requirements\requirements_[yyyy]-[mm].csv'
ezdb_resources_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\resources\resources_[yyyy]-[mm].csv'
ezdb_summaries_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\summaries\summaries_[yyyy]-[mm].csv'
ezdb_supply_plans_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\supply_plans\supply_plans_[yyyy]-[mm].csv'
ezdb_master_lookup_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\DM4\BigData\EZDB\ED_RA\Data\..\EZDB_ED_RA_MasterLookup.xlsx'
log_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\logs\ra_filings_[yyyy]-[mm].log'
cli_logging_criticalities: ERROR,WARNING,INFORMATION
file_logging_criticalities: ERROR,WARNING,INFORMATION
email_log_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\logs\ra_filings_emails.csv'
attachment_log_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\logs\ra_filings_attachments.csv'
consolidation_log_filename: '\\Sf150pyclfs26\PYCLIENTFS\Users\svc_energyRA\ra_filings\data\logs\ra_filings_consolidation_[yyyy]-[mm].csv'
version_controlled_files:
  - ra_monthly_filing
  - cam_rmr
  - month_ahead
  - year_ahead
  - incremental_local
  - supply_plan_system
  - supply_plan_flexible
files_for_archive:
  - configuration_options
  - organizations
  - email_filter
  - ra_monthly_filing
  - month_ahead
  - cam_rmr
  - year_ahead
  - incremental_local
  - supply_plan_system
  - supply_plan_flexible
  - ra_summary
  - caiso_cross_check
  - log
  - email_log
  - attachment_log
  - consolidation_log
...